

main_interfaceV2:
	gcc `pkg-config --cflags gtk4` -o main_interfaceV2 main_interfaceV2.c sources/add_window.c sources/generate_button.c sources/switch_page.c sources/generate_action.c sources/profile.c `pkg-config --libs gtk4` -Iheader/
